export const WORDS = Object.freeze([
  'ls', 'pwd', 'cd', 'echo', 'printf', 'cat', 'less', 'head', 'tail', 'wc',
  'sort', 'uniq', 'cut', 'paste', 'grep', 'rg', 'find', 'which', 'man', 'uptime',
  'python', 'javascript', 'typescript', 'java', 'kotlin', 'scala', 'ruby', 'php', 'perl', 'lua',
  'swift', 'rust', 'golang', 'csharp', 'fsharp', 'sql', 'html', 'css', 'wasm', 'bash',
  'pip', 'poetry', 'node', 'npm', 'npx', 'yarn', 'pnpm', 'bun', 'deno', 'javac',
  'gradle', 'maven', 'composer', 'rustc', 'cargo', 'gofmt', 'gcc', 'clang', 'make', 'cmake',
  'git', 'commit', 'branch', 'merge', 'rebase', 'clone', 'fetch', 'pull', 'push', 'tag',
  'stash', 'diff', 'log', 'status', 'checkout', 'repository', 'remote', 'worktree', 'changeset', 'conflict',
  'http', 'https', 'tcp', 'udp', 'dns', 'ipv4', 'ipv6', 'tls', 'ssl', 'ssh',
  'sftp', 'curl', 'wget', 'ping', 'traceroute', 'socket', 'proxy', 'cookie', 'webhook', 'websocket',
  'header', 'payload', 'request', 'response', 'endpoint', 'rest', 'graphql', 'json', 'xml', 'yaml',
  'toml', 'url', 'uri', 'domain', 'port', 'router', 'subnet', 'gateway', 'latency', 'packet',
  'docker', 'podman', 'kubernetes', 'kubectl', 'helm', 'terraform', 'ansible', 'vagrant', 'container', 'registry',
  'cluster', 'namespace', 'service', 'ingress', 'deployment', 'daemonset', 'statefulset', 'configmap', 'pipeline', 'artifact',
  'sqlite', 'mysql', 'postgres', 'mariadb', 'mongodb', 'redis', 'query', 'table', 'column', 'row',
  'index', 'schema', 'transaction', 'join', 'select', 'aggregate', 'cursor', 'shard', 'partition', 'migration',
  'oauth', 'oidc', 'jwt', 'token', 'hash', 'salt', 'cipher', 'encrypt', 'decrypt', 'certificate',
  'signature', 'session', 'cors', 'csrf', 'xss', 'sandbox', 'permission', 'vault', 'mfa', 'passkey',
]);
